/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class Principal extends javax.swing.JFrame {

    javax.swing.JButton boton_universal = new javax.swing.JButton();
    Pieza[][] tablero = new Pieza[8][8];
    String nombre;
    Pieza[] blancos = new Pieza[5];
    Pieza[] negras = new Pieza[5];
    int contador_blancas = 0;
    int contador_negras = 0;

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Caballo = new javax.swing.JMenuItem();
        Rey = new javax.swing.JMenuItem();
        Peon = new javax.swing.JMenuItem();
        A1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();

        Caballo.setText("Caballo");
        Caballo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaballoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Caballo);

        Rey.setText("Rey");
        Rey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReyActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Rey);

        Peon.setText("Peon");
        Peon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeonActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Peon);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        A1.setBackground(new java.awt.Color(254, 173, 173));
        A1.setForeground(new java.awt.Color(254, 173, 173));
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("BLANCOS");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("NEGRAS");

        A2.setBackground(new java.awt.Color(143, 55, 55));
        A2.setForeground(new java.awt.Color(143, 55, 55));
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2MouseClicked(evt);
            }
        });

        A3.setBackground(new java.awt.Color(254, 173, 173));
        A3.setForeground(new java.awt.Color(254, 254, 254));
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A3MouseClicked(evt);
            }
        });

        A4.setBackground(new java.awt.Color(143, 55, 55));
        A4.setForeground(new java.awt.Color(1, 1, 1));
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A4MouseClicked(evt);
            }
        });

        A5.setBackground(new java.awt.Color(254, 173, 173));
        A5.setForeground(new java.awt.Color(254, 254, 254));
        A5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A5MouseClicked(evt);
            }
        });

        A6.setBackground(new java.awt.Color(143, 55, 55));
        A6.setForeground(new java.awt.Color(1, 1, 1));
        A6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A6MouseClicked(evt);
            }
        });

        A7.setBackground(new java.awt.Color(254, 173, 173));
        A7.setForeground(new java.awt.Color(254, 254, 254));
        A7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A7MouseClicked(evt);
            }
        });

        A8.setBackground(new java.awt.Color(143, 55, 55));
        A8.setForeground(new java.awt.Color(1, 1, 1));
        A8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A8MouseClicked(evt);
            }
        });

        B1.setBackground(new java.awt.Color(143, 55, 55));
        B1.setForeground(new java.awt.Color(143, 55, 55));
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });

        B2.setBackground(new java.awt.Color(254, 173, 173));
        B2.setForeground(new java.awt.Color(254, 173, 173));
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });

        B3.setBackground(new java.awt.Color(143, 55, 55));
        B3.setForeground(new java.awt.Color(143, 55, 55));
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });

        B4.setBackground(new java.awt.Color(254, 173, 173));
        B4.setForeground(new java.awt.Color(254, 173, 173));
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });

        B5.setBackground(new java.awt.Color(143, 55, 55));
        B5.setForeground(new java.awt.Color(143, 55, 55));
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });

        B6.setBackground(new java.awt.Color(254, 173, 173));
        B6.setForeground(new java.awt.Color(254, 173, 173));
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
        });

        B7.setBackground(new java.awt.Color(143, 55, 55));
        B7.setForeground(new java.awt.Color(143, 55, 55));
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7MouseClicked(evt);
            }
        });

        B8.setBackground(new java.awt.Color(254, 173, 173));
        B8.setForeground(new java.awt.Color(254, 173, 173));
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B8MouseClicked(evt);
            }
        });

        C1.setBackground(new java.awt.Color(254, 173, 173));
        C1.setForeground(new java.awt.Color(254, 173, 173));
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C1MouseClicked(evt);
            }
        });

        C2.setBackground(new java.awt.Color(143, 55, 55));
        C2.setForeground(new java.awt.Color(143, 55, 55));
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C2MouseClicked(evt);
            }
        });

        C3.setBackground(new java.awt.Color(254, 173, 173));
        C3.setForeground(new java.awt.Color(254, 173, 173));
        C3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C3MouseClicked(evt);
            }
        });

        C4.setBackground(new java.awt.Color(143, 55, 55));
        C4.setForeground(new java.awt.Color(143, 55, 55));
        C4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C4MouseClicked(evt);
            }
        });

        C5.setBackground(new java.awt.Color(254, 173, 173));
        C5.setForeground(new java.awt.Color(254, 173, 173));
        C5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C5MouseClicked(evt);
            }
        });

        C6.setBackground(new java.awt.Color(143, 55, 55));
        C6.setForeground(new java.awt.Color(143, 55, 55));
        C6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C6MouseClicked(evt);
            }
        });

        C7.setBackground(new java.awt.Color(254, 173, 173));
        C7.setForeground(new java.awt.Color(254, 173, 173));
        C7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C7MouseClicked(evt);
            }
        });

        C8.setBackground(new java.awt.Color(143, 55, 55));
        C8.setForeground(new java.awt.Color(143, 55, 55));
        C8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jRadioButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(270, 270, 270)
                                        .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRadioButton2)
                                            .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(80, 80, 80)
                                .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(540, 540, 540)
                                .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(270, 270, 270)
                                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(360, 360, 360)
                                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(450, 450, 450)
                                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(360, 360, 360)
                                        .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(270, 270, 270)
                                        .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(450, 450, 450)
                                .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(558, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
        boton_universal = A1;
        nombre = "1A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());


    }//GEN-LAST:event_A1MouseClicked

    private void ReyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReyActionPerformed
        int[] pos = new int[2];
        if (this.jRadioButton1.isSelected() == true) {
            Rey rey = new Rey(true);
            if (metodo_validacion_blancas(rey)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Rey(true);
                blancos[contador_blancas] = rey;
                contador_blancas++;
                mover(1);
            } else {
                   JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        } else {
            Rey rey = new Rey(false);
            if (metodo_validacion_negros(rey)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Rey(false);
                negras[contador_negras] = rey;
                contador_negras++;
                mover(1);
            } else {
                   JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        }

    }//GEN-LAST:event_ReyActionPerformed

    private void A2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseClicked
        boton_universal = A2;
        nombre = "2A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());

    }//GEN-LAST:event_A2MouseClicked

    private void A3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseClicked
        boton_universal = A3;
        nombre = "3A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_A3MouseClicked

    private void A4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A4MouseClicked
        boton_universal = A4;
        nombre = "4A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_A4MouseClicked

    private void A5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A5MouseClicked
        boton_universal = A5;
        nombre = "5A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());        // TODO add your handling code here:
    }//GEN-LAST:event_A5MouseClicked

    private void A6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A6MouseClicked
        boton_universal = A6;
        nombre = "6A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_A6MouseClicked

    private void A7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A7MouseClicked
        boton_universal = A7;
        nombre = "7A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_A7MouseClicked

    private void A8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A8MouseClicked
        boton_universal = A8;
        nombre = "8A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_A8MouseClicked

    private void CaballoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaballoActionPerformed
        int[] pos = new int[2];
        if (this.jRadioButton1.isSelected() == true) {
            Caballo cab = new Caballo(true);
            if (metodo_validacion_blancas(cab)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Caballo(true);
                blancos[contador_blancas] = cab;
                contador_blancas++;
                mover(0);
            } else {
                JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        } else {
            Caballo cab = new Caballo(false);
            if (metodo_validacion_negros(cab)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Caballo(false);
                negras[contador_negras] = cab;
                contador_negras++;
                mover(0);
            } else {
                JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        }
    }//GEN-LAST:event_CaballoActionPerformed

    private void PeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeonActionPerformed
        int[] pos = new int[2];
        if (this.jRadioButton1.isSelected() == true) {
            Peon peon = new Peon(true);
            if (metodo_validacion_blancas(peon)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Peon(true);
                blancos[contador_blancas] = peon;
                contador_blancas++;
                mover(2);
            } else {
                JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        } else {
            Peon peon = new Peon(false);
            if (metodo_validacion_negros(peon)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Peon(false);
                negras[contador_negras] = peon;
                contador_negras++;
                mover(2);
            } else {
                JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        }
    }//GEN-LAST:event_PeonActionPerformed

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        boton_universal = B1;
        nombre = "1B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B1MouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        boton_universal = B2;
        nombre = "2B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        boton_universal = B3;
        nombre = "3B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B3MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
        boton_universal = B4;
        nombre = "4B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B4MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        boton_universal = B5;
        nombre = "5B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B5MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
        boton_universal = B6;
        nombre = "6B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B6MouseClicked

    private void B7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseClicked
        boton_universal = B7;
        nombre = "7B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B7MouseClicked

    private void B8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseClicked
        boton_universal = B8;
        nombre = "8B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B8MouseClicked

    private void C1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseClicked
        boton_universal = C1;
        nombre = "1C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C1MouseClicked

    private void C2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseClicked
        boton_universal = C2;
        nombre = "2C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C2MouseClicked

    private void C3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C3MouseClicked
        boton_universal = C3;
        nombre = "3C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C3MouseClicked

    private void C4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C4MouseClicked
        boton_universal = C4;
        nombre = "4C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C4MouseClicked

    private void C5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C5MouseClicked
        boton_universal = C5;
        nombre = "5C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C5MouseClicked

    private void C6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C6MouseClicked
        boton_universal = C6;
        nombre = "6C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C6MouseClicked

    private void C7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C7MouseClicked
        boton_universal = C7;
        nombre = "7C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C7MouseClicked

    private void C8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C8MouseClicked
        boton_universal = C8;
        nombre = "8C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    void mover(int num) {
        if (this.jRadioButton1.isSelected() == false) {
            if (num == 0) {
                boton_universal.setIcon(new ImageIcon("./caballo.negro.png"));
            }
            if (num == 1) {
                boton_universal.setIcon(new ImageIcon("./rey.negra.png"));
            }
            if (num == 2) {
                boton_universal.setIcon(new ImageIcon("./peon.negro.png"));
            }
        } else {
            if (num == 0) {
                boton_universal.setIcon(new ImageIcon("./caballo.blanco.png"));
            }
            if (num == 1) {
                boton_universal.setIcon(new ImageIcon("./rey.blanco.png"));
            }
            if (num == 2) {
                boton_universal.setIcon(new ImageIcon("./peon.blanco.png"));
            }
        }

    }

    void menu(boolean click_izquierdo, Component comp, int x, int y) {
        if (click_izquierdo) {
            this.jPopupMenu1.show(comp, x, y);
        }
    }

    int[] posicion(String palabra) {
        int[] posiciones = new int[2];
        posiciones[1] = Posiciones(palabra.charAt(1));
        posiciones[0] = Posiciones(palabra.charAt(0));
        return posiciones;
    }

    int Posiciones(char letra) {
        if (letra == 'A') {
            return 0;
        }
        if (letra == 'B') {
            return 1;
        }
        if (letra == 'C') {
            return 2;
        }
        if (letra == 'D') {
            return 3;
        }
        if (letra == 'E') {
            return 4;
        }
        if (letra == 'F') {
            return 5;
        }
        if (letra == 'G') {
            return 6;
        }
        if (letra == 'H') {
            return 7;
        }
        if (letra == '1') {
            return 0;
        }
        if (letra == '2') {
            return 1;
        }
        if (letra == '3') {
            return 2;
        }
        if (letra == '4') {
            return 3;
        }
        if (letra == '5') {
            return 4;
        }
        if (letra == '6') {
            return 5;
        }
        if (letra == '7') {
            return 6;
        }
        if (letra == '8') {
            return 7;
        } else {
            return -1;
        }

    }

    boolean metodo_validacion_blancas(Pieza pieza) {
        int contador_caballo = 0;
        int contador_rey = 0;
        int contador_peon = 0;
        int elementos = 0;
        int rey = 0;
        for (int i = 0; i < 5; i++) {
            if (blancos[i] != null) {
                elementos++;
            }
            if (blancos[i] instanceof Rey) {
                rey++;
            }
            if (blancos[i] instanceof Caballo) {
                contador_caballo++;
            }
        }
        if ((elementos == 4 && rey == 0 && !(pieza instanceof Rey)) || elementos == 5) {
            System.out.println("primera");
            return false;

        } else if (pieza instanceof Rey) {
            System.out.println("segunda");
            if (rey == 0) {
                return true;
            } else {
                return false;
            }
        } else if (pieza instanceof Caballo) {
            System.out.println("tercera");
            if (contador_caballo < 2) {
                return true;
            } else {
                return false;
            }
        } else {
            System.out.println("cuarta");
            return true;
        }
    }

    boolean metodo_validacion_negros(Pieza pieza) {
        int contador_caballo = 0;

        int contador_peon = 0;
        int elementos = 0;
        int rey = 0;
        for (int i = 0; i < 5; i++) {
            if (negras[i] != null) {
                elementos++;
            }
            if (negras[i] instanceof Rey) {
                rey++;
            }
            if (negras[i] instanceof Caballo) {
                contador_caballo++;
            }
        }
        if ((elementos == 4 && rey == 0 && !(pieza instanceof Rey)) || elementos == 5) {
            return false;
        } else if (pieza instanceof Rey) {
            if (rey == 0) {
                return true;
            } else {
                return false;
            }
        } else if (pieza instanceof Caballo) {
            if (contador_caballo < 2) {
                return true;
            } else {
                return false;
            }
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JMenuItem Caballo;
    private javax.swing.JMenuItem Peon;
    private javax.swing.JMenuItem Rey;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
