/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                this.tablero[i][j] = new vacia();
            }
        }
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Caballo = new javax.swing.JMenuItem();
        Rey = new javax.swing.JMenuItem();
        Peon = new javax.swing.JMenuItem();
        Borrar = new javax.swing.JMenuItem();
        A1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        A2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        A8 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        D8 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        E6 = new javax.swing.JButton();
        E7 = new javax.swing.JButton();
        E8 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        F8 = new javax.swing.JButton();
        G1 = new javax.swing.JButton();
        G2 = new javax.swing.JButton();
        G3 = new javax.swing.JButton();
        G4 = new javax.swing.JButton();
        G5 = new javax.swing.JButton();
        G6 = new javax.swing.JButton();
        G7 = new javax.swing.JButton();
        G8 = new javax.swing.JButton();
        H1 = new javax.swing.JButton();
        H2 = new javax.swing.JButton();
        H3 = new javax.swing.JButton();
        H4 = new javax.swing.JButton();
        H5 = new javax.swing.JButton();
        H6 = new javax.swing.JButton();
        H7 = new javax.swing.JButton();
        H8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_ComerCaballo = new javax.swing.JButton();
        btn_coronarPeon = new javax.swing.JButton();
        btn_ponerHacke = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        Caballo.setText("Caballo");
        Caballo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaballoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Caballo);

        Rey.setText("Rey");
        Rey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReyActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Rey);

        Peon.setText("Peon");
        Peon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeonActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Peon);

        Borrar.setText("borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Borrar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        A1.setBackground(new java.awt.Color(254, 173, 173));
        A1.setForeground(new java.awt.Color(254, 173, 173));
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });
        getContentPane().add(A1);
        A1.setBounds(70, 20, 90, 80);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("BLANCOS");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(850, 50, 79, 22);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("NEGRAS");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(850, 80, 110, 22);

        A2.setBackground(new java.awt.Color(143, 55, 55));
        A2.setForeground(new java.awt.Color(143, 55, 55));
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2MouseClicked(evt);
            }
        });
        getContentPane().add(A2);
        A2.setBounds(160, 20, 90, 80);

        A3.setBackground(new java.awt.Color(254, 173, 173));
        A3.setForeground(new java.awt.Color(254, 254, 254));
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A3MouseClicked(evt);
            }
        });
        getContentPane().add(A3);
        A3.setBounds(250, 20, 90, 80);

        A4.setBackground(new java.awt.Color(143, 55, 55));
        A4.setForeground(new java.awt.Color(1, 1, 1));
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A4MouseClicked(evt);
            }
        });
        getContentPane().add(A4);
        A4.setBounds(340, 20, 90, 80);

        A5.setBackground(new java.awt.Color(254, 173, 173));
        A5.setForeground(new java.awt.Color(254, 254, 254));
        A5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A5MouseClicked(evt);
            }
        });
        getContentPane().add(A5);
        A5.setBounds(430, 20, 90, 80);

        A6.setBackground(new java.awt.Color(143, 55, 55));
        A6.setForeground(new java.awt.Color(1, 1, 1));
        A6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A6MouseClicked(evt);
            }
        });
        getContentPane().add(A6);
        A6.setBounds(520, 20, 90, 80);

        A7.setBackground(new java.awt.Color(254, 173, 173));
        A7.setForeground(new java.awt.Color(254, 254, 254));
        A7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A7MouseClicked(evt);
            }
        });
        getContentPane().add(A7);
        A7.setBounds(610, 20, 90, 80);

        A8.setBackground(new java.awt.Color(143, 55, 55));
        A8.setForeground(new java.awt.Color(1, 1, 1));
        A8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A8MouseClicked(evt);
            }
        });
        getContentPane().add(A8);
        A8.setBounds(700, 20, 90, 80);

        B1.setBackground(new java.awt.Color(143, 55, 55));
        B1.setForeground(new java.awt.Color(143, 55, 55));
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        getContentPane().add(B1);
        B1.setBounds(70, 100, 90, 80);

        B2.setBackground(new java.awt.Color(254, 173, 173));
        B2.setForeground(new java.awt.Color(254, 173, 173));
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        getContentPane().add(B2);
        B2.setBounds(160, 100, 90, 80);

        B3.setBackground(new java.awt.Color(143, 55, 55));
        B3.setForeground(new java.awt.Color(143, 55, 55));
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });
        getContentPane().add(B3);
        B3.setBounds(250, 100, 90, 80);

        B4.setBackground(new java.awt.Color(254, 173, 173));
        B4.setForeground(new java.awt.Color(254, 173, 173));
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });
        getContentPane().add(B4);
        B4.setBounds(340, 100, 90, 80);

        B5.setBackground(new java.awt.Color(143, 55, 55));
        B5.setForeground(new java.awt.Color(143, 55, 55));
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });
        getContentPane().add(B5);
        B5.setBounds(430, 100, 90, 80);

        B6.setBackground(new java.awt.Color(254, 173, 173));
        B6.setForeground(new java.awt.Color(254, 173, 173));
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
        });
        getContentPane().add(B6);
        B6.setBounds(520, 100, 90, 80);

        B7.setBackground(new java.awt.Color(143, 55, 55));
        B7.setForeground(new java.awt.Color(143, 55, 55));
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7MouseClicked(evt);
            }
        });
        getContentPane().add(B7);
        B7.setBounds(610, 100, 90, 80);

        B8.setBackground(new java.awt.Color(254, 173, 173));
        B8.setForeground(new java.awt.Color(254, 173, 173));
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B8MouseClicked(evt);
            }
        });
        getContentPane().add(B8);
        B8.setBounds(700, 100, 90, 80);

        C1.setBackground(new java.awt.Color(254, 173, 173));
        C1.setForeground(new java.awt.Color(254, 173, 173));
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C1MouseClicked(evt);
            }
        });
        getContentPane().add(C1);
        C1.setBounds(70, 180, 90, 80);

        C2.setBackground(new java.awt.Color(143, 55, 55));
        C2.setForeground(new java.awt.Color(143, 55, 55));
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C2MouseClicked(evt);
            }
        });
        getContentPane().add(C2);
        C2.setBounds(160, 180, 90, 80);

        C3.setBackground(new java.awt.Color(254, 173, 173));
        C3.setForeground(new java.awt.Color(254, 173, 173));
        C3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C3MouseClicked(evt);
            }
        });
        getContentPane().add(C3);
        C3.setBounds(250, 180, 90, 80);

        C4.setBackground(new java.awt.Color(143, 55, 55));
        C4.setForeground(new java.awt.Color(143, 55, 55));
        C4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C4MouseClicked(evt);
            }
        });
        getContentPane().add(C4);
        C4.setBounds(340, 180, 90, 80);

        C5.setBackground(new java.awt.Color(254, 173, 173));
        C5.setForeground(new java.awt.Color(254, 173, 173));
        C5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C5MouseClicked(evt);
            }
        });
        getContentPane().add(C5);
        C5.setBounds(430, 180, 90, 80);

        C6.setBackground(new java.awt.Color(143, 55, 55));
        C6.setForeground(new java.awt.Color(143, 55, 55));
        C6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C6MouseClicked(evt);
            }
        });
        getContentPane().add(C6);
        C6.setBounds(520, 180, 90, 80);

        C7.setBackground(new java.awt.Color(254, 173, 173));
        C7.setForeground(new java.awt.Color(254, 173, 173));
        C7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C7MouseClicked(evt);
            }
        });
        getContentPane().add(C7);
        C7.setBounds(610, 180, 90, 80);

        C8.setBackground(new java.awt.Color(143, 55, 55));
        C8.setForeground(new java.awt.Color(143, 55, 55));
        C8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C8MouseClicked(evt);
            }
        });
        getContentPane().add(C8);
        C8.setBounds(700, 180, 90, 80);

        D1.setBackground(new java.awt.Color(143, 55, 55));
        D1.setForeground(new java.awt.Color(143, 55, 55));
        D1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D1MouseClicked(evt);
            }
        });
        getContentPane().add(D1);
        D1.setBounds(70, 260, 90, 80);

        D2.setBackground(new java.awt.Color(254, 173, 173));
        D2.setForeground(new java.awt.Color(254, 173, 173));
        D2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D2MouseClicked(evt);
            }
        });
        getContentPane().add(D2);
        D2.setBounds(160, 260, 90, 80);

        D3.setBackground(new java.awt.Color(143, 55, 55));
        D3.setForeground(new java.awt.Color(143, 55, 55));
        D3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D3MouseClicked(evt);
            }
        });
        getContentPane().add(D3);
        D3.setBounds(250, 260, 90, 80);

        D4.setBackground(new java.awt.Color(254, 173, 173));
        D4.setForeground(new java.awt.Color(254, 173, 173));
        D4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D4MouseClicked(evt);
            }
        });
        getContentPane().add(D4);
        D4.setBounds(340, 260, 90, 80);

        D5.setBackground(new java.awt.Color(143, 55, 55));
        D5.setForeground(new java.awt.Color(143, 55, 55));
        D5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D5MouseClicked(evt);
            }
        });
        getContentPane().add(D5);
        D5.setBounds(430, 260, 90, 80);

        D6.setBackground(new java.awt.Color(254, 173, 173));
        D6.setForeground(new java.awt.Color(254, 173, 173));
        D6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D6MouseClicked(evt);
            }
        });
        getContentPane().add(D6);
        D6.setBounds(520, 260, 90, 80);

        D7.setBackground(new java.awt.Color(143, 55, 55));
        D7.setForeground(new java.awt.Color(143, 55, 55));
        D7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D7MouseClicked(evt);
            }
        });
        getContentPane().add(D7);
        D7.setBounds(610, 260, 90, 80);

        D8.setBackground(new java.awt.Color(254, 173, 173));
        D8.setForeground(new java.awt.Color(254, 173, 173));
        D8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D8MouseClicked(evt);
            }
        });
        getContentPane().add(D8);
        D8.setBounds(700, 260, 90, 80);

        E1.setBackground(new java.awt.Color(254, 173, 173));
        E1.setForeground(new java.awt.Color(254, 173, 173));
        E1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E1MouseClicked(evt);
            }
        });
        getContentPane().add(E1);
        E1.setBounds(70, 340, 90, 80);

        E2.setBackground(new java.awt.Color(143, 55, 55));
        E2.setForeground(new java.awt.Color(143, 55, 55));
        E2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2MouseClicked(evt);
            }
        });
        getContentPane().add(E2);
        E2.setBounds(160, 340, 90, 80);

        E3.setBackground(new java.awt.Color(254, 173, 173));
        E3.setForeground(new java.awt.Color(254, 173, 173));
        E3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E3MouseClicked(evt);
            }
        });
        getContentPane().add(E3);
        E3.setBounds(250, 340, 90, 80);

        E4.setBackground(new java.awt.Color(143, 55, 55));
        E4.setForeground(new java.awt.Color(143, 55, 55));
        E4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E4MouseClicked(evt);
            }
        });
        getContentPane().add(E4);
        E4.setBounds(340, 340, 90, 80);

        E5.setBackground(new java.awt.Color(254, 173, 173));
        E5.setForeground(new java.awt.Color(254, 173, 173));
        E5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E5MouseClicked(evt);
            }
        });
        getContentPane().add(E5);
        E5.setBounds(430, 340, 90, 80);

        E6.setBackground(new java.awt.Color(143, 55, 55));
        E6.setForeground(new java.awt.Color(143, 55, 55));
        E6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E6MouseClicked(evt);
            }
        });
        getContentPane().add(E6);
        E6.setBounds(520, 340, 90, 80);

        E7.setBackground(new java.awt.Color(254, 173, 173));
        E7.setForeground(new java.awt.Color(254, 173, 173));
        E7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E7MouseClicked(evt);
            }
        });
        getContentPane().add(E7);
        E7.setBounds(610, 340, 90, 80);

        E8.setBackground(new java.awt.Color(143, 55, 55));
        E8.setForeground(new java.awt.Color(143, 55, 55));
        E8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E8MouseClicked(evt);
            }
        });
        getContentPane().add(E8);
        E8.setBounds(700, 340, 90, 80);

        F1.setBackground(new java.awt.Color(143, 55, 55));
        F1.setForeground(new java.awt.Color(143, 55, 55));
        F1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F1MouseClicked(evt);
            }
        });
        getContentPane().add(F1);
        F1.setBounds(70, 420, 90, 80);

        F2.setBackground(new java.awt.Color(254, 173, 173));
        F2.setForeground(new java.awt.Color(254, 173, 173));
        F2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F2MouseClicked(evt);
            }
        });
        getContentPane().add(F2);
        F2.setBounds(160, 420, 90, 80);

        F3.setBackground(new java.awt.Color(143, 55, 55));
        F3.setForeground(new java.awt.Color(143, 55, 55));
        F3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F3MouseClicked(evt);
            }
        });
        getContentPane().add(F3);
        F3.setBounds(250, 420, 90, 80);

        F4.setBackground(new java.awt.Color(254, 173, 173));
        F4.setForeground(new java.awt.Color(254, 173, 173));
        F4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F4MouseClicked(evt);
            }
        });
        getContentPane().add(F4);
        F4.setBounds(340, 420, 90, 80);

        F5.setBackground(new java.awt.Color(143, 55, 55));
        F5.setForeground(new java.awt.Color(143, 55, 55));
        F5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F5MouseClicked(evt);
            }
        });
        getContentPane().add(F5);
        F5.setBounds(430, 420, 90, 80);

        F6.setBackground(new java.awt.Color(254, 173, 173));
        F6.setForeground(new java.awt.Color(254, 173, 173));
        F6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F6MouseClicked(evt);
            }
        });
        getContentPane().add(F6);
        F6.setBounds(520, 420, 90, 80);

        F7.setBackground(new java.awt.Color(143, 55, 55));
        F7.setForeground(new java.awt.Color(143, 55, 55));
        F7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F7MouseClicked(evt);
            }
        });
        getContentPane().add(F7);
        F7.setBounds(610, 420, 90, 80);

        F8.setBackground(new java.awt.Color(254, 173, 173));
        F8.setForeground(new java.awt.Color(254, 173, 173));
        F8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F8MouseClicked(evt);
            }
        });
        getContentPane().add(F8);
        F8.setBounds(700, 420, 90, 80);

        G1.setBackground(new java.awt.Color(254, 173, 173));
        G1.setForeground(new java.awt.Color(254, 173, 173));
        G1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G1MouseClicked(evt);
            }
        });
        getContentPane().add(G1);
        G1.setBounds(70, 500, 90, 80);

        G2.setBackground(new java.awt.Color(143, 55, 55));
        G2.setForeground(new java.awt.Color(143, 55, 55));
        G2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G2MouseClicked(evt);
            }
        });
        getContentPane().add(G2);
        G2.setBounds(160, 500, 90, 80);

        G3.setBackground(new java.awt.Color(254, 173, 173));
        G3.setForeground(new java.awt.Color(254, 173, 173));
        G3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G3MouseClicked(evt);
            }
        });
        getContentPane().add(G3);
        G3.setBounds(250, 500, 90, 80);

        G4.setBackground(new java.awt.Color(143, 55, 55));
        G4.setForeground(new java.awt.Color(143, 55, 55));
        G4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G4MouseClicked(evt);
            }
        });
        getContentPane().add(G4);
        G4.setBounds(340, 500, 90, 80);

        G5.setBackground(new java.awt.Color(254, 173, 173));
        G5.setForeground(new java.awt.Color(254, 173, 173));
        G5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G5MouseClicked(evt);
            }
        });
        getContentPane().add(G5);
        G5.setBounds(430, 500, 90, 80);

        G6.setBackground(new java.awt.Color(143, 55, 55));
        G6.setForeground(new java.awt.Color(143, 55, 55));
        G6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G6MouseClicked(evt);
            }
        });
        getContentPane().add(G6);
        G6.setBounds(520, 500, 90, 80);

        G7.setBackground(new java.awt.Color(254, 173, 173));
        G7.setForeground(new java.awt.Color(254, 173, 173));
        G7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G7MouseClicked(evt);
            }
        });
        getContentPane().add(G7);
        G7.setBounds(610, 500, 90, 80);

        G8.setBackground(new java.awt.Color(143, 55, 55));
        G8.setForeground(new java.awt.Color(143, 55, 55));
        G8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G8MouseClicked(evt);
            }
        });
        getContentPane().add(G8);
        G8.setBounds(700, 500, 90, 80);

        H1.setBackground(new java.awt.Color(143, 55, 55));
        H1.setForeground(new java.awt.Color(143, 55, 55));
        H1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H1MouseClicked(evt);
            }
        });
        getContentPane().add(H1);
        H1.setBounds(70, 580, 90, 80);

        H2.setBackground(new java.awt.Color(254, 173, 173));
        H2.setForeground(new java.awt.Color(254, 173, 173));
        H2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H2MouseClicked(evt);
            }
        });
        getContentPane().add(H2);
        H2.setBounds(160, 580, 90, 80);

        H3.setBackground(new java.awt.Color(143, 55, 55));
        H3.setForeground(new java.awt.Color(143, 55, 55));
        H3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H3MouseClicked(evt);
            }
        });
        getContentPane().add(H3);
        H3.setBounds(250, 580, 90, 80);

        H4.setBackground(new java.awt.Color(254, 173, 173));
        H4.setForeground(new java.awt.Color(254, 173, 173));
        H4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H4MouseClicked(evt);
            }
        });
        getContentPane().add(H4);
        H4.setBounds(340, 580, 90, 80);

        H5.setBackground(new java.awt.Color(143, 55, 55));
        H5.setForeground(new java.awt.Color(143, 55, 55));
        H5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H5MouseClicked(evt);
            }
        });
        getContentPane().add(H5);
        H5.setBounds(430, 580, 90, 80);

        H6.setBackground(new java.awt.Color(254, 173, 173));
        H6.setForeground(new java.awt.Color(254, 173, 173));
        H6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H6MouseClicked(evt);
            }
        });
        getContentPane().add(H6);
        H6.setBounds(520, 580, 90, 80);

        H7.setBackground(new java.awt.Color(143, 55, 55));
        H7.setForeground(new java.awt.Color(143, 55, 55));
        H7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H7MouseClicked(evt);
            }
        });
        getContentPane().add(H7);
        H7.setBounds(610, 580, 90, 80);

        H8.setBackground(new java.awt.Color(254, 173, 173));
        H8.setForeground(new java.awt.Color(254, 173, 173));
        H8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H8MouseClicked(evt);
            }
        });
        getContentPane().add(H8);
        H8.setBounds(700, 580, 90, 80);

        jLabel1.setText("Evaluaciones");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(860, 138, 73, 17);

        btn_ComerCaballo.setText("Comer Caballo");
        btn_ComerCaballo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ComerCaballoMouseClicked(evt);
            }
        });
        getContentPane().add(btn_ComerCaballo);
        btn_ComerCaballo.setBounds(860, 188, 120, 31);

        btn_coronarPeon.setText("Coronar Peon");
        btn_coronarPeon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_coronarPeonMouseClicked(evt);
            }
        });
        btn_coronarPeon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_coronarPeonActionPerformed(evt);
            }
        });
        getContentPane().add(btn_coronarPeon);
        btn_coronarPeon.setBounds(860, 249, 120, 31);

        btn_ponerHacke.setText("Poner en hacke");
        getContentPane().add(btn_ponerHacke);
        btn_ponerHacke.setBounds(860, 309, 98, 31);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 17, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("6");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 450, 17, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 290, 17, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 210, 17, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("2");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 130, 17, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 530, 17, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("B");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 670, 20, 29);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("5");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 360, 17, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("8");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 610, 17, 29);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("C");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 670, 20, 29);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("D");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(380, 670, 20, 29);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("E");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(470, 670, 20, 29);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setText("F");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(560, 670, 20, 29);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel15.setText("G");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(650, 670, 20, 29);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setText("H");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(740, 670, 20, 29);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("A");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(100, 670, 20, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
        boton_universal = A1;
        nombre = "1A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_A1MouseClicked

    private void ReyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReyActionPerformed
        int[] pos = new int[2];
        if (this.jRadioButton1.isSelected() == true) {
            Rey rey = new Rey(true);
            if (metodo_validacion_blancas(rey)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Rey(true);
                blancos[contador_blancas] = rey;
                contador_blancas++;
                mover(1);
            } else {
                JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        } else {
            Rey rey = new Rey(false);
            if (metodo_validacion_negros(rey)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Rey(false);
                negras[contador_negras] = rey;
                contador_negras++;
                mover(1);
            } else {
                JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        }

    }//GEN-LAST:event_ReyActionPerformed

    private void A2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseClicked
        boton_universal = A2;
        nombre = "2A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());

    }//GEN-LAST:event_A2MouseClicked

    private void A3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseClicked
        boton_universal = A3;
        nombre = "3A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_A3MouseClicked

    private void A4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A4MouseClicked
        boton_universal = A4;
        nombre = "4A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_A4MouseClicked

    private void A5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A5MouseClicked
        boton_universal = A5;
        nombre = "5A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());        // TODO add your handling code here:
    }//GEN-LAST:event_A5MouseClicked

    private void A6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A6MouseClicked
        boton_universal = A6;
        nombre = "6A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_A6MouseClicked

    private void A7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A7MouseClicked
        boton_universal = A7;
        nombre = "7A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_A7MouseClicked

    private void A8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A8MouseClicked
        boton_universal = A8;
        nombre = "8A";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_A8MouseClicked

    private void CaballoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaballoActionPerformed
        int[] pos = new int[2];
        if (this.jRadioButton1.isSelected() == true) {
            Caballo cab = new Caballo(true);
            if (metodo_validacion_blancas(cab)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Caballo(true);
                blancos[contador_blancas] = cab;
                contador_blancas++;
                mover(0);
            } else {
                JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        } else {
            Caballo cab = new Caballo(false);
            if (metodo_validacion_negros(cab)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Caballo(false);
                negras[contador_negras] = cab;
                contador_negras++;
                mover(0);
            } else {
                JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        }
    }//GEN-LAST:event_CaballoActionPerformed

    private void PeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeonActionPerformed
        int[] pos = new int[2];
        if (this.jRadioButton1.isSelected() == true) {
            Peon peon = new Peon(true);
            if (metodo_validacion_blancas(peon)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Peon(true);
                blancos[contador_blancas] = peon;
                contador_blancas++;
                mover(2);
            } else {
                JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        } else {
            Peon peon = new Peon(false);
            if (metodo_validacion_negros(peon)) {
                pos = posicion(nombre);
                tablero[pos[0]][pos[1]] = new Peon(false);
                negras[contador_negras] = peon;
                contador_negras++;
                mover(2);
            } else {
                JOptionPane.showMessageDialog(null, "MOvimiento invalido");
            }
        }
    }//GEN-LAST:event_PeonActionPerformed

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        boton_universal = B1;
        nombre = "1B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B1MouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        boton_universal = B2;
        nombre = "2B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        boton_universal = B3;
        nombre = "3B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B3MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
        boton_universal = B4;
        nombre = "4B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B4MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        boton_universal = B5;
        nombre = "5B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B5MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
        boton_universal = B6;
        nombre = "6B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B6MouseClicked

    private void B7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseClicked
        boton_universal = B7;
        nombre = "7B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B7MouseClicked

    private void B8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseClicked
        boton_universal = B8;
        nombre = "8B";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_B8MouseClicked

    private void C1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseClicked
        boton_universal = C1;
        nombre = "1C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C1MouseClicked

    private void C2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseClicked
        boton_universal = C2;
        nombre = "2C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C2MouseClicked

    private void C3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C3MouseClicked
        boton_universal = C3;
        nombre = "3C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C3MouseClicked

    private void C4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C4MouseClicked
        boton_universal = C4;
        nombre = "4C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C4MouseClicked

    private void C5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C5MouseClicked
        boton_universal = C5;
        nombre = "5C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C5MouseClicked

    private void C6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C6MouseClicked
        boton_universal = C6;
        nombre = "6C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C6MouseClicked

    private void C7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C7MouseClicked
        boton_universal = C7;
        nombre = "7C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C7MouseClicked

    private void C8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C8MouseClicked
        boton_universal = C8;
        nombre = "8C";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_C8MouseClicked

    private void D1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D1MouseClicked
        boton_universal = D1;
        nombre = "1D";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_D1MouseClicked

    private void D2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D2MouseClicked
        boton_universal = D2;
        nombre = "2D";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_D2MouseClicked

    private void D3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D3MouseClicked
        boton_universal = D3;
        nombre = "3D";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_D3MouseClicked

    private void D4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D4MouseClicked
        boton_universal = D4;
        nombre = "4D";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_D4MouseClicked

    private void D5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D5MouseClicked
        boton_universal = D5;
        nombre = "5D";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_D5MouseClicked

    private void D6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D6MouseClicked
        boton_universal = D6;
        nombre = "6D";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_D6MouseClicked

    private void D7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D7MouseClicked
        boton_universal = D7;
        nombre = "7D";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_D7MouseClicked

    private void D8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D8MouseClicked
        boton_universal = D8;
        nombre = "8D";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_D8MouseClicked

    private void E1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E1MouseClicked
        boton_universal = E1;
        nombre = "1E";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_E1MouseClicked

    private void E2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2MouseClicked
        boton_universal = E2;
        nombre = "2E";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_E2MouseClicked

    private void E3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E3MouseClicked
        boton_universal = E3;
        nombre = "3E";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_E3MouseClicked

    private void E4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E4MouseClicked
        boton_universal = E4;
        nombre = "4E";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_E4MouseClicked

    private void E5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E5MouseClicked
        boton_universal = E5;
        nombre = "5E";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_E5MouseClicked

    private void E6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E6MouseClicked
        boton_universal = E6;
        nombre = "6E";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_E6MouseClicked

    private void E7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E7MouseClicked
        boton_universal = E7;
        nombre = "7E";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_E7MouseClicked

    private void E8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E8MouseClicked
        boton_universal = E8;
        nombre = "8E";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_E8MouseClicked

    private void F1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F1MouseClicked
        boton_universal = F1;
        nombre = "1F";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_F1MouseClicked

    private void F2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F2MouseClicked
        boton_universal = F2;
        nombre = "2F";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_F2MouseClicked

    private void F3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F3MouseClicked
        boton_universal = F3;
        nombre = "3F";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_F3MouseClicked

    private void F4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F4MouseClicked
        boton_universal = F4;
        nombre = "4F";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_F4MouseClicked

    private void F5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F5MouseClicked
        boton_universal = F5;
        nombre = "5F";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_F5MouseClicked

    private void F6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F6MouseClicked
        boton_universal = F6;
        nombre = "6F";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_F6MouseClicked

    private void F7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F7MouseClicked
        boton_universal = F7;
        nombre = "7F";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_F7MouseClicked

    private void F8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F8MouseClicked
        boton_universal = F8;
        nombre = "8F";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_F8MouseClicked

    private void G1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G1MouseClicked
        boton_universal = G1;
        nombre = "1G";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_G1MouseClicked

    private void G2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G2MouseClicked
        boton_universal = G2;
        nombre = "2G";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_G2MouseClicked

    private void G3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G3MouseClicked
        boton_universal = G3;
        nombre = "3G";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_G3MouseClicked

    private void G4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G4MouseClicked
        boton_universal = G4;
        nombre = "4G";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_G4MouseClicked

    private void G5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G5MouseClicked
        boton_universal = G5;
        nombre = "5G";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_G5MouseClicked

    private void G6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G6MouseClicked
        boton_universal = G6;
        nombre = "6G";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_G6MouseClicked

    private void G7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G7MouseClicked
        boton_universal = G7;
        nombre = "7G";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_G7MouseClicked

    private void G8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G8MouseClicked
        boton_universal = G8;
        nombre = "8G";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_G8MouseClicked

    private void H1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H1MouseClicked
        boton_universal = H1;
        nombre = "1H";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_H1MouseClicked

    private void H2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H2MouseClicked
        boton_universal = H2;
        nombre = "2H";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_H2MouseClicked

    private void H3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H3MouseClicked
        boton_universal = H3;
        nombre = "3H";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_H3MouseClicked

    private void H4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H4MouseClicked
        boton_universal = H4;
        nombre = "4H";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_H4MouseClicked

    private void H5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H5MouseClicked
        boton_universal = H5;
        nombre = "5H";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_H5MouseClicked

    private void H6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H6MouseClicked
        boton_universal = H6;
        nombre = "6H";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_H6MouseClicked

    private void H7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H7MouseClicked
        boton_universal = H7;
        nombre = "7H";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_H7MouseClicked

    private void H8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H8MouseClicked
        boton_universal = H8;
        nombre = "8H";
        menu(evt.isMetaDown(), evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_H8MouseClicked

    private void btn_ComerCaballoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ComerCaballoMouseClicked
        nodos = new Lista();
        TreeNode temporal = new TreeNode();
        int beforeEvaluation = countHorses(tablero);
        int afterEvaluation = 0;
        boolean continuePlaying = true;
        nuevo = new mapa(tablero, new Movimiento(0, 0, 0, 0));
        mapeo = new MyTree(new TreeNode(nuevo));

        while (continuePlaying) {
            mapeo.preorder(null, nodos);
            for (int i = 0; i < nodos.getSize(); i++) {
                temporal = (TreeNode) nodos.get(i);
                System.out.println(temporal.getValue().getClass().toString());
                afterEvaluation = countHorses(((mapa) (temporal.getValue())).getTablero());
                if (beforeEvaluation != afterEvaluation) {
                    continuePlaying = false;
                    nodoGuardado = temporal;
                    JOptionPane.showMessageDialog(this, "Ya se han comido un caballo", "ALERTA", JOptionPane.WARNING_MESSAGE);
                    break;
                }
                this.simularPartida((TreeNode) nodos.get(i));
            }
            nodos = new Lista();
        }
        JOptionPane.showMessageDialog(this, "Se termino el proceso", "", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btn_ComerCaballoMouseClicked

    private void btn_coronarPeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_coronarPeonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_coronarPeonActionPerformed

    private void btn_coronarPeonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_coronarPeonMouseClicked
        nodos = new Lista();
        TreeNode temporal = new TreeNode();
        int beforeEvaluation = countHorses(tablero);
        int afterEvaluation = 0;
        boolean continuePlaying = true;
        nuevo = new mapa(tablero, new Movimiento(0, 0, 0, 0));
        mapeo = new MyTree(new TreeNode(nuevo));

        while (continuePlaying) {
            mapeo.preorder(null, nodos);
            for (int i = 0; i < nodos.getSize(); i++) {
                temporal = (TreeNode) nodos.get(i);

                if (esreina(temporal)) {
                    continuePlaying = false;
                    nodoGuardado = temporal;
                    JOptionPane.showMessageDialog(this, "Ya un peón se ha coronado", "ALERTA", JOptionPane.WARNING_MESSAGE);
                    break;
                }
                this.simularPartida((TreeNode) nodos.get(i));
            }
            nodos = new Lista();
        }
        JOptionPane.showMessageDialog(this, "Se termino el proceso", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_coronarPeonMouseClicked

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        int[] pos = new int[2];
        pos = posicion(nombre);
        System.out.println("no");
        if (tablero[pos[0]][pos[1]] != null) {
            System.out.println("per");
            
            if (tablero[pos[0]][pos[1]] instanceof Caballo) {
                System.out.println("si");
                if(tablero[pos[0]][pos[1]].isEsblanca()==true){
                    for (int i = 0; i < 5; i++) {
                        if(blancos[i] instanceof Caballo){
                            blancos[i]=null;
                            contador_blancas--;
                            break;
                        }
                    }
                }else{
                    for (int i = 0; i < 5; i++) {
                        if(negras[i] instanceof Caballo){
                            negras[i]=null;
                            contador_negras--;
                            break;
                        }
                    }
                }
            } else if (tablero[pos[0]][pos[1]] instanceof Peon) {
                if(tablero[pos[0]][pos[1]].isEsblanca()==true){
                    for (int i = 0; i < 5; i++) {
                        if(blancos[i] instanceof Peon){
                            blancos[i]=null;
                            contador_blancas--;
                            break;
                        }
                    }
                }else{
                    for (int i = 0; i < 5; i++) {
                        if(negras[i] instanceof Peon){
                            negras[i]=null;
                            contador_negras--;
                            break;
                        }
                    }
                }
            } else if (tablero[pos[0]][pos[1]] instanceof Rey) {
                if(tablero[pos[0]][pos[1]].isEsblanca()==true){
                    for (int i = 0; i < 5; i++) {
                        if(blancos[i] instanceof Rey){
                            blancos[i]=null;
                            contador_blancas--;
                            break;
                        }
                    }
                }else{
                    for (int i = 0; i < 5; i++) {
                        if(negras[i] instanceof Rey){
                            negras[i]=null;
                            contador_negras--;
                            break;
                        }
                    }
                }
            }
            tablero[pos[0]][pos[1]] =null;
            boton_universal.setIcon(null);
        }
        System.out.println(contador_negras);
        System.out.println(contador_blancas);
    }//GEN-LAST:event_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    void mover(int num) {
        if (this.jRadioButton1.isSelected() == false) {
            if (num == 0) {
                boton_universal.setIcon(new ImageIcon("./caballo.negro.png"));
            }
            if (num == 1) {
                boton_universal.setIcon(new ImageIcon("./rey.negra.png"));
            }
            if (num == 2) {
                boton_universal.setIcon(new ImageIcon("./peon.negro.png"));
            }
        } else {
            if (num == 0) {
                boton_universal.setIcon(new ImageIcon("./caballo.blanco.png"));
            }
            if (num == 1) {
                boton_universal.setIcon(new ImageIcon("./rey.blanco.png"));
            }
            if (num == 2) {
                boton_universal.setIcon(new ImageIcon("./peon.blanco.png"));
            }
        }

    }

    void menu(boolean click_izquierdo, Component comp, int x, int y) {
        if (click_izquierdo) {
            this.jPopupMenu1.show(comp, x, y);
        }
    }

    int[] posicion(String palabra) {
        int[] posiciones = new int[2];
        posiciones[1] = Posiciones(palabra.charAt(1));
        posiciones[0] = Posiciones(palabra.charAt(0));
        return posiciones;
    }

    int Posiciones(char letra) {
        if (letra == 'A') {
            return 0;
        }
        if (letra == 'B') {
            return 1;
        }
        if (letra == 'C') {
            return 2;
        }
        if (letra == 'D') {
            return 3;
        }
        if (letra == 'E') {
            return 4;
        }
        if (letra == 'F') {
            return 5;
        }
        if (letra == 'G') {
            return 6;
        }
        if (letra == 'H') {
            return 7;
        }
        if (letra == '1') {
            return 0;
        }
        if (letra == '2') {
            return 1;
        }
        if (letra == '3') {
            return 2;
        }
        if (letra == '4') {
            return 3;
        }
        if (letra == '5') {
            return 4;
        }
        if (letra == '6') {
            return 5;
        }
        if (letra == '7') {
            return 6;
        }
        if (letra == '8') {
            return 7;
        } else {
            return -1;
        }
    }

    boolean metodo_validacion_blancas(Pieza pieza) {
        int contador_caballo = 0;
        int contador_rey = 0;
        int contador_peon = 0;
        int elementos = 0;
        int rey = 0;
        for (int i = 0; i < 5; i++) {
            if (blancos[i] != null) {
                elementos++;
            }
            if (blancos[i] instanceof Rey) {
                rey++;
            }
            if (blancos[i] instanceof Caballo) {
                contador_caballo++;
            }
        }
        if ((elementos == 4 && rey == 0 && !(pieza instanceof Rey)) || elementos == 5) {
            System.out.println("primera");
            return false;

        } else if (pieza instanceof Rey) {
            System.out.println("segunda");
            if (rey == 0) {
                return true;
            } else {
                return false;
            }
        } else if (pieza instanceof Caballo) {
            System.out.println("tercera");
            if (contador_caballo < 2) {
                return true;
            } else {
                return false;
            }
        } else {
            System.out.println("cuarta");
            return true;
        }
    }

    public void simularPartida(TreeNode evaluando) {
        realizarJugada(evaluando, turno);
        turno = turno == 1 ? 2 : 1;
    }

    public void realizarJugada(TreeNode board, int turno) {
        int x1, y1;
        nodoUniversal = board;
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                if (turno == 1 && ((mapa) board.getValue()).getTablero()[i][j].isEsblanca()
                        || turno == 2 && ((mapa) board.getValue()).getTablero()[i][j].isEsblanca() == false) {
                    x1 = i;
                    y1 = j;
                    for (int k = 0; k < 8; k++) {
                        for (int l = 0; l < 8; l++) {
                            if (((mapa) board.getValue()).getTablero()[x1][y1].isValidMovement(((mapa) board.getValue()).getTablero(),
                                    x1, y1, k, l, turno)) {
                                if (checkNextSquare(((mapa) board.getValue()).getTablero(), turno, k, l) == 1
                                        || checkNextSquare(((mapa) board.getValue()).getTablero(), turno, k,
                                                l) == 2) {
                                    nuevo = new mapa(((mapa) board.getValue()).getTablero(), new Movimiento(x1, y1, k, l));
                                    moverCasilla(nuevo.getTablero(), x1, y1, k, l);
                                    nodoUniversal.addSon(nuevo);
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    public int countHorses(Pieza[][] board) {
        int horses = 0;

        for (int i = 0; i < 8; i++) {
            for (int k = 0; k < 8; k++) {
                if (board[i][k] instanceof Caballo) {
                    horses++;
                }
            }
        }
        return horses;
    }

    public void moverCasilla(Pieza[][] tablero, int x1, int y1, int x2, int y2) {
        tablero[x2][y2] = tablero[x1][y1];
        tablero[x1][y1] = new vacia();
    }

    public int checkNextSquare(Pieza[][] tablero, int turno, int x2, int y2) {
        int retorno = 0;
        if (turno == 1) {//si es blanca
            if (tablero[x2][y2] instanceof vacia) {
                retorno = 1; //Si la siguiente casilla esta vacia
            } else if (tablero[x2][y2].isEsblanca() == false) {
                retorno = 2;
            } else if (tablero[x2][y2].isEsblanca()) {
                retorno = 3;
            }

        } else if (tablero[x2][y2] == null) {

        } else//si es negra
         if (tablero[x2][y2] instanceof vacia) {

                retorno = 1; //Si la siguiente casilla esta vacia
            } else if (tablero[x2][y2].isEsblanca()) {
                retorno = 2;
            } else if (tablero[x2][y2].isEsblanca() == false) {
                retorno = 3;
            }
        return retorno;
    }

    boolean metodo_validacion_negros(Pieza pieza
    ) {
        int contador_caballo = 0;

        int contador_peon = 0;
        int elementos = 0;
        int rey = 0;
        for (int i = 0; i < 5; i++) {
            if (negras[i] != null) {
                elementos++;
            }
            if (negras[i] instanceof Rey) {
                rey++;
            }
            if (negras[i] instanceof Caballo) {
                contador_caballo++;
            }
        }
        if ((elementos == 4 && rey == 0 && !(pieza instanceof Rey)) || elementos == 5) {
            return false;
        } else if (pieza instanceof Rey) {
            if (rey == 0) {
                return true;
            } else {
                return false;
            }
        } else if (pieza instanceof Caballo) {
            if (contador_caballo < 2) {
                return true;
            } else {
                return false;
            }
        }
        return true;

    }

    boolean esreina(TreeNode nodo) {
        Pieza[][] tab = ((mapa) nodo.getValue()).getTablero();
        for (int i = 0; i < 7; i++) {
            for (int j = 0; j < 7; j++) {
                if (tab[i][j] instanceof Peon && i == 7) {
                    return true;
                }
                if (tab[i][j] instanceof Peon && i == 0) {
                    return true;
                }
            }
        }
        return false;
    }

    Lista getPath(TreeNode nodo_amostrar, TreeNode raiz) {
        Lista lista_de_padres = new Lista();
        lista_de_padres.push(nodo_amostrar);
        TreeNode nodo_seleccionado = new TreeNode();
        nodo_seleccionado = nodo_amostrar;
        while (nodo_seleccionado != raiz) {
            lista_de_padres.push(nodo_seleccionado.getParent());
            nodo_seleccionado = nodo_seleccionado.getParent();
        }
        return lista_de_padres;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JButton A8;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JMenuItem Borrar;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JMenuItem Caballo;
    private javax.swing.JButton D1;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton D5;
    private javax.swing.JButton D6;
    private javax.swing.JButton D7;
    private javax.swing.JButton D8;
    private javax.swing.JButton E1;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton E5;
    private javax.swing.JButton E6;
    private javax.swing.JButton E7;
    private javax.swing.JButton E8;
    private javax.swing.JButton F1;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JButton F8;
    private javax.swing.JButton G1;
    private javax.swing.JButton G2;
    private javax.swing.JButton G3;
    private javax.swing.JButton G4;
    private javax.swing.JButton G5;
    private javax.swing.JButton G6;
    private javax.swing.JButton G7;
    private javax.swing.JButton G8;
    private javax.swing.JButton H1;
    private javax.swing.JButton H2;
    private javax.swing.JButton H3;
    private javax.swing.JButton H4;
    private javax.swing.JButton H5;
    private javax.swing.JButton H6;
    private javax.swing.JButton H7;
    private javax.swing.JButton H8;
    private javax.swing.JMenuItem Peon;
    private javax.swing.JMenuItem Rey;
    private javax.swing.JButton btn_ComerCaballo;
    private javax.swing.JButton btn_coronarPeon;
    private javax.swing.JButton btn_ponerHacke;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
 javax.swing.JButton boton_universal = new javax.swing.JButton();
    Pieza[][] tablero = new Pieza[8][8];
    String nombre;
    Pieza[] blancos = new Pieza[5];
    Pieza[] negras = new Pieza[5];
    int contador_blancas = 0;
    int contador_negras = 0;
    int turno = 1;
    MyTree mapeo = new MyTree();
    TreeNode nodoUniversal = new TreeNode();
    mapa nuevo = new mapa();
    Lista nodos = new Lista();
    TreeNode nodoGuardado = new TreeNode();
}
